name: Sign NuGet packages
description: 'Signs NuGet packages with the Particular key.'
inputs:
  client-id:
    description: 'Part of the Azure Key Vault credentials required for package signing'
    required: true
  tenant-id:
    description: 'Part of the Azure Key Vault credentials required for package signing'
    required: true
  client-secret:
    description: 'Part of the Azure Key Vault credentials required for package signing'
    required: true
  certificate-name:
    description: 'Part of the Azure Key Vault credentials required for package signing'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install NuGetKeyVaultSignTool
      shell: pwsh
      run: dotnet tool install --global NuGetKeyVaultSignTool
    - name: Sign NuGet Packages
      shell: pwsh
      run: |
        cd nugets

        NuGetKeyVaultSignTool sign $path `
        --file-digest sha256 `
        --timestamp-rfc3161 http://timestamp.digicert.com `
        --timestamp-digest sha256 `
        --azure-key-vault-url https://particularcodesigning.vault.azure.net `
        --azure-key-vault-client-id ${{ inputs.client-id }} `
        --azure-key-vault-tenant-id ${{ inputs.tenant-id }} `
        --azure-key-vault-client-secret ${{ inputs.client-secret }} `
        --azure-key-vault-certificate ${{ inputs.certificate-name }}

        cd ..
