name: CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 6.0.x
      - name: Build fake NuGet packages
        run: dotnet build test-project --configuration Release
      - name: Run
        uses: ./
        with:
          client-id: ${{ secrets.AZURE_KEY_VAULT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_KEY_VAULT_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_KEY_VAULT_CLIENT_SECRET }}
          certificate-name: ${{ secrets.AZURE_KEY_VAULT_CERTIFICATE_NAME }}
      - name: Publish NuGet packages
        uses: actions/upload-artifact@v4.6.2
        with:
          name: nugets-${{ matrix.os }}
          path: nugets/*
          retention-days: 1
      - name: Validate package signature
        shell: pwsh
        run: |
          dotnet nuget verify nugets/TestLib.1.0.0.nupkg
          dotnet nuget verify nugets/TestLib2.1.0.0.nupkg
