name: CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-20.04
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.x
      - name: Build fake NuGet package
        run: dotnet build test-package
      - name: Run
        uses: ./
        with:
          client-id: ${{ secrets.AZURE_KEY_VAULT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_KEY_VAULT_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_KEY_VAULT_CLIENT_SECRET }}
          certificate-name: ${{ secrets.AZURE_KEY_VAULT_CERTIFICATE_NAME }}
      - name: Publish NuGet packages
        uses: actions/upload-artifact@v3.1.0
        with:
          name: nugets
          path: nugets/*
          retention-days: 1
      - name: Validate package signature
        shell: pwsh
        run: dotnet nuget verify nugets/*.nupkg
