name: CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-20.04
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Create fake artifacts
        shell: pwsh
        run: |
          mkdir nugets
          echo "This is not really a NuGet package" > nugets/Fake.Package1.nupkg
          echo "This is not really a NuGet package" > nugets/Fake.Package2.nupkg
      - name: Run
        uses: ./
        with:
          azure-key-vault-credentials: ${{ secrets.AZURE_KEY_VAULT_CREDENTIALS }}
      - name: Validate
        shell: pwsh
        run: |
          echo "Temp"
